name: Release Mycelium Node

# Этот блок дает права нашему роботу-публикатору. Ошибка №1 - исправлена.
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libayatana-appindicator3-dev \
            # Устанавливаем правильную, а не новую версию WebKit
            libwebkit2gtk-4.1-dev \
            # Устанавливаем тот самый пакет, которого не хватало. Ошибка №2 - исправлена.
            libjavascriptcoregtk-4.1-dev

      - name: Set PKG_CONFIG_PATH for Ubuntu
        if: matrix.platform.os == 'ubuntu-latest'
        # Устанавливаем ту самую переменную окружения. Ошибка №3 - исправлена.
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Install frontend dependencies
        run: npm install

      - name: Build and Release with Tauri Action
        # Это самый надежный способ публикации. Ошибка №4 - исправлена.
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Mycelium Node v__VERSION__'
          releaseBody: 'Стабильный релиз v0.1.1. Автоматическая сборка после полной отладки CI/CD.'
          releaseDraft: false
          prerelease: false
